### ISSUE TITLE
Would be super neat to declare url in templatable way

### ISSUE THREAD

**Issue by tonycox** [BananaOps/homer-k8s#103]
**Is your feature request related to a problem? Please describe.**
I'm doing a lot of dynamic k8s configuration along with kustomize scripts. and it would be super helpful if url part in items was templatable.

**Describe the solution you'd like**
Let's say I have this example
```
apiVersion: homer.bananaops.io/v1alpha1
kind: HomerServices
metadata:
  name: super-duper-app
  namespace: apps
spec:
  groups:
  - icon: fas fa-code-branch
    items:
    - keywords: apps
      name: super duper app
      target: _blank
      url: /super-duper-app/
    name: Supers
```
And I would like to create a PR in my env with some adjustments in this crd.

```
apiVersion: homer.bananaops.io/v1alpha1
kind: HomerServices
metadata:
  name: pr-123-super-duper-app
  namespace: apps
spec:
  groups:
  - icon: fas fa-code-branch
    items:
    - keywords: apps
      name: super duper app
      target: _blank
      url: /pr-123-super-duper-app/
    name: Supers
```
With kustomize with its guideline and recommendations it is quite hard to add such string interpolation. If it is a single definition there is no problem, when its 10+ becomes problematic :( 

With templating I could just declare it as:

```
apiVersion: homer.bananaops.io/v1alpha1
kind: HomerServices
metadata:
  name: pr-123-super-duper-app
  namespace: apps
spec:
  groups:
  - icon: fas fa-code-branch
    items:
    - keywords: apps
      name: super duper app
      target: _blank
      url: /{{metadata.name}}/
    name: Supers
```

**Describe alternatives you've considered**

**Additional context**
