### ISSUE TITLE
Changes not been recognized

### ISSUE THREAD

**Issue by weyderfs** [BananaOps/homer-k8s#31]
**Describe the bug**
Any change custom in the `homer.config:` works. The docs aren't clear, maybe I'm wrong, but if you made some _change_ in the section bellow, the things would be change.

I've been tried:

- `helm upgrade -i .....`
- `helm delete .... and helm upgrade -i again`
- After made deployment kill the pod manually...without success.

```yaml
homer: 
  # -- Structured homer configuration, takes precedence over `homer.config`
  structuredConfig: {}
  config: |
    title: "App dashboard"
    subtitle: "Homer k8s"
    # documentTitle: "Welcome" # Customize the browser tab text
    logo: "https://raw.githubusercontent.com//bastienwirtz/homer/main/public/logo.png"
    # Alternatively a fa icon can be provided:
    # icon: "fas fa-skull-crossbones"

    header: true # Set to false to hide the header
    # Optional: Different hotkey for search, defaults to "/"
    # hotkey:
    #   search: "Shift"
    footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

    columns: "3" # "auto" or number (must be a factor of 12: 1, 2, 3, 4, 6, 12)
    connectivityCheck: true # whether you want to display a message when the apps are not accessible anymore (VPN disconnected for example).
                            # You should set it to true when using an authentication proxy, it also reloads the page when a redirection is detected when checking connectivity.
[...]

```
