### ISSUE TITLE
To allow specifying the Homer 'b4bz/homer' image in Helm chart

### ISSUE THREAD

**Issue by jyje** [BananaOps/homer-k8s#80]
**Is your feature request related to a problem? Please describe.**
In the Helm chart, it'd be great to clearly define the `repository` and `tag` for the Homer image.

**Describe the solution you'd like**
Set the values like this:

```yaml
# ...
homer:
  image:
    repository: b4bz/homer
    pullPolicy: IfNotPresent
    tag: latest
# ...
```

**Describe alternatives you've considered**
None so far.

**Additional context**
- Here's why this is helpful:
  - It can lock the Homer dashboard to a specific tag for production.
  - It can test new images for the forked-Homer dashboard.
